### ISSUE TITLE
README feedback 

### ISSUE THREAD

**Issue by stevemart** [IBM/build-knowledge-base-with-domain-specific-documents#6]
I went through this code pattern, here are my thoughts:

1. State early on where the data came from. It's in the `data` folder, but has no attribution. Please state where it's from and properly attribute the data set.

2. Link out to https://pypi.org/project/mammoth/ when you mention it.

3. (nit pick) Add spaces before braces "html(semi-structured format)" should be "html (semi-structured format)"

4. (nit pick) use either `.docx` or DOCX, not docx.

5. The video isn't rendering, use: 

```
[![](http://img.youtube.com/vi/lC2-h2ac_Jg/0.jpg)](https://youtu.be/lC2-h2ac_Jg)
```

6. Remove Step 1 (sign up)

7. Step 3 -- I updated one of our notebook repos: https://github.com/IBM/kafka-streaming-click-analysis#run-using-a-jupyter-notebook-in-the-ibm-watson-studio -- please use this as a template as it includes updated screenshots

8. I'd put the configuration files in the data folder, it's all static content anyway. I'd also rename those folders to be lowercase.

**Comment by Neha-Setia** [comment]
@stevemart  fixed everything :). Please check!

**Comment by stevemart** [comment]
Hey @Neha-Setia 

a few more comments, also, please use pull reviews instead of committing to master, i'm happy to review :)

1. For the references, please link out to https://en.wikipedia.org/wiki/Suresh_H._Advani and https://en.wikipedia.org/wiki/Oncology as those are the two documents in Archive.zip. 

So in the README do something like...

```
The data used in this code pattern comes from two Wikipedia articles. The first is taken from the Wikipedia page of oncologist [Suresh H. Advani](https://en.wikipedia.org/wiki/Suresh_H._Advani) the second is from the Wikipedia page about [Oncology](https://en.wikipedia.org/wiki/Oncology). These files are zipped up as [Archive.zip](data/Archive.zip).
```

2. Looks fixed.

3. I'm still seeing a few example of missing spaces, like `Natural Language Processing(NLP)` should be `Natural Language Processing (NLP)`.

4. Looks fixed.

5. Looks fixed.

6. Looks fixed.

7. I think you can remove step 2.2 since you don't need a spark service.

8. Looks fixed.

**Comment by stevemart** [comment]
@Neha-Setia looks good to me, closing this bug via 57d0941cf0bc99b9f0047eaa32a0edf8e58f1c9d

@Neha-Setia re: PRs, check youtube, tons of content about it https://www.youtube.com/watch?v=FQsBmnZvBdc and if you're just editing a simple README doc you can do it from the github web interface.
